# Generated by Django 4.2.13 on 2025-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_imageurl_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pollVotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
