# Generated by Django 4.2.13 on 2025-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='documentName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='documentUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
