# Generated by Django 4.2.13 on 2025-07-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_profile_email_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
