# Generated by Django 4.2.13 on 2025-07-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_profile_friends_message_deleted_for_everyone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deleted_for_users',
            field=models.TextField(blank=True, default=''),
        ),
    ]
